print("โปรแกรมคำนวณหาค่าอัตราเร็ว จากสูตร v = s/t")
Distance = float(input("กรอกระยะทาง(s) ที่มีค่าตั้งแต่ 1 ขึ้นไป:"))
Time = float(input("กรอกระยะเวลา(t) ที่มีค่าตั้งแต่ 1 ขึ้นไป:"))
print("Distance(s) = ",Distance,"km")
print("Time(t) = ",Time,"h")
print("Velocity(v) = ",int(Distance/Time),"km/h")